# Generated by Django 3.1.5 on 2021-01-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210107_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_txt',
            new_name='choice',
        ),
    ]
